dev_mode: false

# Environment variables that EVERY pod will know about, NOT secrets!
env:
  OPENID_ISSUER_URL: "https://connect.test.surfconext.nl/"
  OPENID_CLIENT_ID: "thesisfair.local"
  OPENID_REDIRECT_URL: "https://thesisfair.ivi.uva.nl/sso/loggedin"
  OPENID_RESOURCE: "https://thesisfair.ivi.uva.nl"
  DATANOSE_API_URL: "https://api.datanose.nl/"
  MAILHOST: "webmail.uva.nl"
  MAILPORT: "587"
  MAILUSER: "SRV-THESIS"

# Azure settings
azure:
  keyvaultName: keyvaultName
  resourceGroup: resourceGroupName
  subscriptionId: subscriptionId
  tenantId: tenantId
  clientId: clientId
  identityName: identityName

# Simple definition of essentials for the microservice architecture (msa)
msa:
  API_gateway:
    secrets:
      - name: thesisfair-jwt-secret
        key: JWT_SECRET
      - name: thesisfair-oidc-secret
        key: OPENID_CLIENT_SECRET
  user_service:
    storage: 4Gi
    secrets:
      - name: thesisfair-jwt-secret
        key: JWT_SECRET
      - name: thesisfair-mail-password
        key: MAILPASS
  entity_service:
  event_service:
  project_service:
    secrets:
      - name: thesisfair-mail-password
        key: MAILPASS
  vote_service:
  payment_service:
    secrets:
      - name: thesisfair-payments-token
        key: PAYMENT_API_TOKEN
  frontend_service:
    env:
      PORT: 3000
      REACT_APP_API_ENDPOINT: "https://localhost:3000/api/"

# Container registry where production-ready containers are kept, defaults to
# fnwicr.azurecr.io, though we have no access to this CR, so the containers
# aren't actually on there  yet
prod:
  cr: "fnwicr.azurecr.io/thesisfair"
  host: "thesisfair.ivi.uva.nl"
  pullPolicy: Always

# When dev mode is enabled, the container repository for
# microservices is changed to dev.cr (presumably a local CR)
# Additionally, the microservice directories from the specified thesisfair code
# repository (presumably also local) will be mounted to the running containers
# so changes made to the code are reflected in the deployment
dev:
  cr: "localhost:5001"
  pullPolicy: Always
  repository: "/home/docker/thesisfair"

  secrets:
    MAILPASS:
    OPENID_CLIENT_SECRET:
    JWT_SECRET:
    PAYMENT_API_TOKEN:
