trigger:
  - main

variables:
  - group: k8s

pool: k8s

jobs:
  - job: build
    steps:
      - script: |
          npm i
          npm run build
        displayName: 'Build library'
        workingDirectory: ./msa/libraries/thesisfair-api
      - script: |
          ./scripts/build-production.sh .
        displayName: 'Build containers'
      - script: |
          ./scripts/push-production.sh .
        displayName: 'Push containers'
      - script: |
          set -euxo pipefail
          VERSION="0.${BUILD_BUILDNUMBER}"
          helm package --version "${VERSION}" --app-version "${VERSION}" chart
          helm push "thesisfair-${VERSION}.tgz" oci://fnwicr.azurecr.io/helm
          curl "https://k8s.datanose.nl/gitops-updater?name=thesisfair&secret=${UPDATER_SECRET}&version=${VERSION}"
        displayName: Build Helm chart and push to registry
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
        env:
          UPDATER_SECRET: $(DEPLOY_SECRET)
