env:
  OPENID_ISSUER_URL: "https://connect.test.surfconext.nl/"
  OPENID_CLIENT_ID: "thesisfair.local"
  OPENID_REDIRECT_URL: "https://thesisfair.ivi.uva.nl/sso/loggedin"
  OPENID_RESOURCE: "https://thesisfair.ivi.uva.nl"
  MAILHOST: "webmail.uva.nl"
  MAILPORT: "587"
  MAILUSER: "SRV-THESIS"

azure:
  keyvaultName: keyvaultName
  resourceGroup: resourceGroupName
  subscriptionId: subscriptionId
  tenantId: tenantId
  clientId: clientId
  identityName: identityName
