{{- if not .Values.dev_mode }}
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: thesisfair-identity-aks-kv
  namespace: "{{ .Release.Namespace }}"
spec:
  type: 0
  resourceID: "/subscriptions/{{ .Values.azure.subscriptionId }}/resourcegroups/{{ .Values.azure.resourceGroup }}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{{ .Values.azure.identityName }}"
  clientID: {{ .Values.azure.clientId }}
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: thesisfair-identity-aks-kv-binding
  namespace: "{{ .Release.Namespace }}"
spec:
  azureIdentity: thesisfair-identity-aks-kv
  selector: thesisfair-azure-kv
{{- end }}
