apiVersion: networking.k8s.io/v1

# Route requests to the frontend or api
kind: Ingress
metadata:
  name: thesisfair
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
    - hosts:
        - "thesisfair.ivi.uva.nl"
      secretName: ingress-tls-csi-thesisfair
  rules:
    - host: thesisfair.ivi.uva.nl
      http:
        paths:
          - path: /api/(.*)
            pathType: Prefix
            backend:
              service:
                name: thesisfair-api
                port:
                  number: 80
          - path: /(sso/.*)
            pathType: Prefix
            backend:
              service:
                name: thesisfair-api
                port:
                  number: 80
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: thesisfair-frontend
                port:
                  number: 3000
