apiVersion: networking.k8s.io/v1

# Route requests to the frontend or api
kind: Ingress
metadata:
  name: thesisfair
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: 5m
    nginx.ingress.kubernetes.io/server-snippet: |
      add_header X-Frame-Options "DENY";
      add_header Content-Security-Policy "default-src 'self' 'unsafe-inline'; connect-src 'self' wss://thesisfair.ivi.uva.nl:3000" always;
spec:
  {{ if not .Values.dev_mode }}
  tls:
    - hosts:
        - {{ .Values.prod.host }}
      secretName: ingress-tls-csi-thesisfair
  {{ end }}
  rules:
    - {{ if not .Values.dev_mode }}host: thesisfair.ivi.uva.nl{{ end }}
      http:
        paths:
          - path: /api/(.*)
            pathType: Prefix
            backend:
              service:
                name: thesisfair-api
                port:
                  number: 80
          - path: /(sso/.*)
            pathType: Prefix
            backend:
              service:
                name: thesisfair-api
                port:
                  number: 80
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: thesisfair-frontend
                port:
                  number: 3000
