{{ $Release := .Release }}
{{ if not .Values.dev_mode }}
apiVersion: v1

# Make a claim to the mongodb storage
kind: PersistentVolumeClaim
metadata:
  name: database-storage
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 50Mi

{{ range $name, $service := .Values.msa }}
{{ if $service }}
{{ if $service.storage }}
---
apiVersion: v1

kind: PersistentVolumeClaim
metadata:
  name: {{ $name | kebabcase }}-data-storage
  namespace: {{ $Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: {{ $service.storage }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}
