{{ $Values := .Values }}
{{ if not .Values.dev_mode }}
apiVersion: "storage.k8s.io/v1"

# Define a storage class for database storage on Azure
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: database-storage
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
  location: europe
  storageAccount: {{ .Values.azure.storageAccount }}
  resourceGroup: {{ .Values.azure.resourceGroup }}

---
apiVersion: v1

# Mount some storage for the mongo database
kind: PersistentVolume
metadata:
  name: database-storage
spec:
  storageClassName: database-storage
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  local:
    path: {{ $Values.dev.repository }}/msa/libraries
  capacity:
    storage: 20Mi
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "kubernetes.io/hostname"
              operator: In
              values:
                - minikube
---
apiVersion: v1

# Make a claim to the mongodb storage
kind: PersistentVolumeClaim
metadata:
  name: database-storage
spec:
  storageClassName: 
  accessModes:
    - ReadWriteOnce
  volumeName: database-storage
  resources:
    requests:
      storage: 20Gi

{{ end }}
