{{ if not .Values.dev_mode }}
apiVersion: v1

# Make a claim to the mongodb storage
kind: PersistentVolumeClaim
metadata:
  name: database-storage
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 50Mi
{{ end }}
