{{ $Release := .Release }}
apiVersion: v1

# Set up a service to expose thesisfair to the nginx ingress
kind: Service
metadata:
  name: thesisfair-frontend
  namespace: {{ .Release.namespace }}
spec:
  ports:
    - port: {{ .Values.msa.frontend_service.env.PORT }}
      targetPort: 3000
  selector:
    app: frontend-service

---
apiVersion: v1

# Set up a service to expose the api (from api-gateway) to nginx ingress (and
# thus the frontend)
kind: Service
metadata:
  name: thesisfair-api
  namespace: {{ .Release.namespace }}
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: api-gateway

---
apiVersion: v1

# Set up a service to expose the database internally to the api deployment
kind: Service
metadata:
  name: database
  namespace: {{ .Release.namespace }}
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: database

---
apiVersion: v1

# Set up a service to expose the messaging queue internally to the api
# deployment
kind: Service
metadata:
  name: messaging-queue
  namespace: {{ .Release.namespace }}
spec:
  ports:
    - port: 5672
      targetPort: 5672
  selector:
    app: messaging-queue

{{ if not .Values.dev_mode }}
{{ range $name, $service := .Values.msa }}
{{ if $service }}
{{ if $service.storage }}
---
apiVersion: v1

kind: Service
metadata:
  name: {{ $name | kebabcase }}
  namespace: {{ $Release.Namespace }}
spec:
  {{- if $service.port }}
  ports:
    - port: {{ $service.port }}
      targetPort: {{ $service.port }}
  {{- end }}
  selector:
    app: {{ $name | kebabcase }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}
