apiVersion: v1

# Set up a service to expose thesisfair to the nginx ingress
kind: Service
metadata:
  name: thesisfair-frontend
spec:
  ports:
    - port: {{ .Values.msa.services.frontend_service.env.PORT }}
      targetPort: {{ .Values.port }}
  selector:
    app: frontend-service

---
apiVersion: v1

# Set up a service to expose the api (from api-gateway) to nginx ingress (and
# thus the frontend)
kind: Service
metadata:
  name: thesisfair-api
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: api-gateway

---
apiVersion: v1

# Set up a service to expose the database internally to the api deployment
kind: Service
metadata:
  name: database
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: database

---
apiVersion: v1

# Set up a service to expose the messaging queue internally to the api
# deployment
kind: Service
metadata:
  name: messaging-queue
spec:
  ports:
    - port: 5672
      targetPort: 5672
  selector:
    app: messaging-queue

---
apiVersion: v1

# Set up a service to expose the mailhog smtp server to the API internally
kind: Service
metadata:
  name: smtp-server
spec:
  ports:
    - port: 8025
      targetPort: 8025
  selector:
    app: mailhog
