---
- name: Install docker on ubuntu
  hosts: thesisfair
  become: true

  tasks:
    - name: Update server
      apt:
        update_cache: true
        upgrade: safe

    - name: Install dependencies
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory

    - name: Add Docker's GPG key
      shell:
        cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        creates: /etc/apt/keyrings/docker.gpg

    - name: Set up docker repository
      shell:
        cmd: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        creates: /etc/apt/sources.list.d/docker.list

    - name: Install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        update_cache: true

    - name: Start and enable docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Initialize application directory
      file:
        path: /opt/thesisfair
        state: directory

    - name: Partition disk
      parted:
        device: /dev/disk/azure/scsi1/lun0
        label: gpt
        number: 1
        fs_type: xfs
        state: present

    - name: Format disk
      filesystem:
        dev: /dev/disk/azure/scsi1/lun0-part1
        fstype: xfs

    - name: Add disk to fstab
      blockinfile:
        backup: true
        path: /etc/fstab
        block: /dev/disk/azure/scsi1/lun0-part1 /opt/thesisfair xfs defaults 0 2
      register: fstabUpdate

    - name: Remount all disks
      shell:
        cmd: mount -a
      when: fstabUpdate.changed

    - name: Compose directory
      file:
        path: /opt/thesisfair/compose
        state: directory

    - name: Data directory
      file:
        path: /opt/thesisfair/data
        state: directory

    - name: Service data directories
      file:
        path: /opt/thesisfair/data/{{ item }}
        state: directory
      loop:
        - db
        - entityService
        - traefik
        - userService
        - eventService

    - name: Prometheus data directory
      file:
        path: /opt/thesisfair/data/prometheus
        state: directory
        owner: nobody
        group: nogroup

    - name: Grafana data directory
      file:
        path: /opt/thesisfair/data/grafana
        state: directory
        owner: 472
        group: root

    - name: Backup directory
      file:
        path: /opt/thesisfair/backup
        state: directory

    - name: Schedule backup
      cron:
        name: Backup
        user: root
        minute: 0
        hour: 2
        job: cd /opt/thesisfair/compose && ./backup.sh >> /opt/thesisfair/backup/out.txt
