entrypoints:
  web:
    address: ':80'
    http:
      redirections:
        entrypoint:
          to: webSec
          scheme: https
  webSec:
    address: ':443'
    http:
      tls:
        certResolver: 'letsencrypt'
  metrics:
    address: ':8082'

certificatesResolvers:
  letsencrypt:
    acme:
      email: q.r.coltof@uva.nl
      storage: /data/acme.json
      httpChallenge:
        entryPoint: web

providers:
  docker:
    watch: true
    exposedByDefault: false
  file:
    directory: /dynamic-config
    watch: true

accessLog: {}

metrics:
  prometheus:
    entryPoint: metrics
    addRoutersLabels: true

api:
  insecure: true
