version: '3'
services:
  api_gateway:
    build:
      context: ./API_gateway
      args:
        NODE_ENV: ${NODE_ENV}
    entrypoint: npm run ${NODE_CMD}
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - OPENID_ISSUER_URL=${OPENID_ISSUER_URL}
      - OPENID_CLIENT_ID=${OPENID_CLIENT_ID}
      - OPENID_CLIENT_SECRET=${OPENID_CLIENT_SECRET}
      - OPENID_REDIRECT_URL=${OPENID_REDIRECT_URL}
      - OPENID_RESOURCE=${OPENID_RESOURCE}
    labels:
      traefik.enable: 'true'
      traefik.http.routers.apiGateway.rule: (PathPrefix(`/api`) || PathPrefix(`/sso`))
      traefik.http.routers.apiGateway.middlewares: apiGatewayStrip
      traefik.http.middlewares.apiGatewayStrip.stripprefix.prefixes: /api
    volumes:
      - ./API_gateway/src:/app/src
      - ./libraries:/libraries
    networks:
      - thesisfair

networks:
  thesisfair:
    name: thesisfair
    external: true
