version: '3'
services:
  api-event:
    build:
      context: ./event_service
      args:
        NODE_ENV: ${NODE_ENV}
    entrypoint: npm run ${NODE_CMD}
    environment:
      - mongodbConStr=mongodb://mongodb/event_service
    volumes:
      - ./event_service/src:/app/src
      - ./event_service/data:/app/data
      - ./libraries:/libraries
    networks:
      - default
      - thesisfair

  mongodb:
    image: mongo
    command: --quiet --logpath /dev/null
    restart: unless-stopped

    ports:
      - 27017:27017

networks:
  thesisfair:
    name: thesisfair
    external: true
