FROM node:alpine

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

EXPOSE 80
ENV PORT 80

WORKDIR /app
COPY ./package*.json ./
RUN npm ci

# ARG REACT_APP_API_ENDPOINT=http://localhost:3000/
# ENV REACT_APP_API_ENDPOINT=${REACT_APP_API_ENDPOINT}

COPY public .
COPY src .

CMD ["npm", "run", "start"]
